spring:
  thymeleaf:
    mode: HTML
    cache: false
  profiles:
    active: dev
  messages:
    basename: messages
  mail:
  #以下缺省的为个人密码信息，自行填写本人的密码信息即可
    host: smtp.qq.com
    port: 587
    username: 
    password: 
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465 #端口号465或587
    properties.mail.display.sendmail: aaa #可以任意
    properties.mail.display.sendname: bbb #可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true #开启SSL
    default-encoding: utf-8
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true



comment.avatar: /images/avatar.png
server:
  maxHttpHeaderSize: 10240
